version: '3'

services:
  web:
    restart: always
    build: 
      context: ./src
      args:
        gitbranch: master
    env_file:
      - production.env
    networks:
      - nginx_network
    image: ${DOCKER_REGISTRY}/web:v${VERSION_TAG}

  nginx:
    restart: always
    build: 
      context: ./nginx
      args:
        nginxconf: douglasdaly.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - nginx_network
    image: ${DOCKER_REGISTRY}/nginx:v${VERSION_TAG}

networks:
  nginx_network:
    driver: bridge
