version: '3'

services:
  web:
    restart: always
    build: 
      context: ./src
      args:
        gitbranch: master
    entrypoint: make local_start
    environment:
      - N_WORKERS=3
    networks:
      - nginx_network
    volumes:
      - static_volume:/src/douglasdaly/static
      - media_volume:/src/douglasdaly/media
    image: web:v${VERSION_TAG}-dev
  
  nginx:
    restart: always
    build: 
      context: ./nginx
      args:
        nginxconf: douglasdaly-debug.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - nginx_network
    volumes:
      - static_volume:/src/douglasdaly/static
      - media_volume:/src/douglasdaly/media
    image: nginx:v${VERSION_TAG}-dev

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
  media_volume: