version: '3'

services:
  web:
    image: ${DOCKER_REGISTRY}/web:v${APP_VERSION_TAG}
    build: 
      context: ./src
      args:
        gitbranch: master
    restart: always
    networks:
      - nginx_network
    
  revproxy:
    image: ${DOCKER_REGISTRY}/nginx:v${NGINX_VERSION_TAG}-${CERT_TYPE}
    restart: always
    build: 
      context: ./nginx
      args:
        cert_type: ${CERT_TYPE}
    environment:
      - CERTBOT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
