version: '2'

services:
  web:
    restart: always
    build: ./src
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - /src/
    environment:
      - N_WORKERS=3

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
