version: '3'

services:
  web:
    restart: always
    build: 
      context: ./src
      args:
        gitbranch: master
    networks:
      - nginx_network
    image: ${DOCKER_REGISTRY}/web:v${APP_VERSION_TAG}

  revproxy:
    restart: always
    build: 
      context: ./nginx
      args:
        cert_type: static
        cert_file: ${CERT_FILE}
        cert_key: ${CERT_KEY}
        nginxconf: www.douglasdaly.conf
    environment:
      - CERTBOT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - web
    networks:
      - nginx_network
    image: ${DOCKER_REGISTRY}/nginx:v${NGINX_VERSION_TAG}

networks:
  nginx_network:
    driver: bridge
