version: '3'

services:
  web:
    restart: always
    build: 
      context: ./src
      args:
        gitbranch: master
    environment:
      - N_WORKERS=3
    env_file:
      - staging.env
    networks:
      - nginx_network
    image: ${DOCKER_REGISTRY}/web:v${VERSION_TAG}-stage
  
  nginx:
    restart: always
    build: 
      context: ./nginx
      args:
        nginxconf: douglasdaly.conf
    environment:
      - CERTBOT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - nginx_network
    image: ${DOCKER_REGISTRY}/nginx:v${VERSION_TAG}-stage

networks:
  nginx_network:
    driver: bridge
